apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
  namespace: matrix

spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 8000
  selector:
    app: gateway