apiVersion: v1
kind: Service
metadata:
  labels:
    app: message
  name: message
  namespace: matrix

spec:
  type: NodePort
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 8000
  selector:
    app: message