apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: matrix
  name: bff
  labels:
    app: bff
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: bff
      labels:
        app: bff
    spec:
      imagePullSecrets:
        - name: coding-docker
      containers:
        - name: bff
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsUser: 1000
            runAsNonRoot: true
          image: cloudbase-100023518199-docker.pkg.coding.net/matrix/matrix/bff
          env:
            - name: timestep
              value: "1"
          command: [ "/home/app/bff" ]
          args:
            - -nacos
            - nacos-headless.matrix.svc.cluster.local:8848
            - -trace
            - http://127.0.0.1:14268/api/traces
            - -token
            - abc
            - -namespace
            - abc
            - -group
            - matrix
            - -username
            - user
            - -password
            - abc
            - -log
            - tencent
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 8000
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 8000
      restartPolicy: Always
      serviceAccountName: matrix
  selector:
    matchLabels:
      app: bff
