apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: matrix
  name: creation
  labels:
    app: creation
spec:
  replicas: 3
  template:
    metadata:
      name: creation
      labels:
        app: creation
    spec:
      imagePullSecrets:
        - name: coding-docker
      containers:
        - name: creation
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsUser: 1000
            runAsNonRoot: true
          image: cloudbase-100023518199-docker.pkg.coding.net/matrix/matrix/creation
          command: ["/home/app/creation"]
          args:
            - -nacos
            - nacos-headless.matrix.svc.cluster.local:8848
            - -trace
            - http://127.0.0.1:14268/api/traces
            - -token
            - abc
            - -namespace
            - abc
            - -group
            - matrix
            - -username
            - user
            - -password
            - abc
            - -log
            - tencent
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /v1/get/creation/healthz
              port: 8000
      restartPolicy: Always
  selector:
    matchLabels:
      app: creation
